# Default project 

# Import presets
defaults:
  - hydra/job_logging: custom
  - data/dataset: flag_recognition_data
  - data/sampler: shuffle_sampler
  - train/trainer: default
  - train/criterion: nll_loss
  - train/metric: classification
  - model: LSTM

# MLflow configs
experiment:
  name: Default

# Training configs
train:
  batch_size: 12
  epochs: 300
  save_best_ckpt: True
  num_workers: 2
  ckpt_path: best_ckpt.pth
  eval: False
  optimizer:
    name: adam
    lr: 0.001
    # lr: 0.0001
    decay: 0.0001

# Model configs
model:
  initial_ckpt: 